### PR TITLE
HIV Workshop/Conference

### PR DESCRIPTION
**Pull request by greenkidneybean**
I've added an upcoming event that may be of interest: Linking Computational and Experimental Biology in HIV Research, a workshop/lecture series from March 29-30 at the NCI campus in Frederick.

### CODE REVIEW

**Comment by greenkidneybean** [comment]
[ACVP Computational symposium Mar 29-30.pdf](https://github.com/NIHDataScienceSIG/nihdatasciencesig.github.io/files/1790662/ACVP.Computational.symposium.Mar.29-30.pdf)

**Comment by seandavi** [comment]
Great contribution, @greenkidneybean. Thx.

**Comment by greenkidneybean** [comment]
Thanks Sean!  Let me know if there's anything else I should include in future pull requests to make for a smoother merge (not sure what to do about .YAML dependencies).  Cheers!

**Comment by seandavi** [comment]
Everything was fine except that the date field must be a single date. The site was a weekend of work, so it is VERY rough and needs to be hardened, documented, and streamlined, but....

Thanks for the courage in making the pull request! Keep them coming.

**Pull request merged**
